export {default as Sesame} from './studies/sesame.png'
export {default as LJB} from './studies/ljb.png'
export {default as FSB} from './studies/fsb.png'
export {default as Meta} from './certifications/Meta.png'
export {default as ITS} from './certifications/ItSpecialist.png'
export {default as TechClub} from './associative-life/Sesame-Tech-Club.png'
export {default as AIESEC} from './associative-life/Aiesec.png'
export {default as AOC} from './associative-life/AOC.png'
 export {default as Confledis} from './experience/Confledis.png'
export {default as Infogerance} from './experience/Infogerance.png'
export {default as MondeEnBouche} from './projects/Home.png'
export {default as AmanaInsurance} from './projects/Amana Insurance.png'