export {default as PersonalPhoto} from './my-photo.png'
export {default as Sesame} from './studies/sesame.png'
export {default as LJB} from './studies/ljb.png'
export {default as FSB} from './studies/fsb.png'
export {default as Meta} from './certifications/Meta.png'
export {default as ITS} from './certifications/ItSpecialist.png'
export {default as TechClub} from './associative-life/Sesame-Tech-Club.png'
export {default as AIESEC} from './associative-life/Aiesec.png'
export {default as AOC} from './associative-life/AOC.png'
 export {default as Confledis} from './experience/Confledis.png'
export {default as Infogerance} from './experience/Infogerance.png'
export {default as OldPortfolio} from './projects/old-personal-portfolio.png'
export {default as MondeEnBouche} from './projects/le-monde-en-bouche-desktop.png'
export {default as MondeEnBoucheMobile} from './projects/le-monde-en-bouche-phone.png'
export {default as RestaurantManagement} from './projects/restaurant management.png'
export {default as AmanaInsurance} from './projects/Amana Insurance.png'
export {default as HotelManagement} from './projects/Hotel Management.png'
export {default as MunicipalityManagement} from './projects/Municipalité.png'
export {default as TennisCLub} from './projects/Tennis Club App.png'
export { default as Ecommerce} from './projects/E-commerce.jpg'
export {default as NavbarAvatar} from "./navbar-avatar.png"
export {default as VictorHugo} from './famous-persons/Victor_Hugo.jpg'
export {default as Einstein} from './famous-persons/einstein.webp'
export {default as Pele} from './famous-persons/pele.jpg'
export {default as OperahWinfrey} from './famous-persons/operah-winfrey.png'